[paths]
xlsx = D:\Эфир\Траффик-листы
src  = D:\Эфир\Ролики
dst  = D:\Эфир\Готово

[clipboard]
customline1 = customline1
customline2 = customline2
customline3 = customline3

[ffmpeg]
ffmpeg =
ffprobe =

[assembly]
middle = Reklama_RTR
opener = D:\Эфир\Обёртки\открывашка.mxf
closer = D:\Эфир\Обёртки\закрывашка.mxf
backup_source = D:\Эфир\Резерв
output_dir =
video_mode = copy
audio_layout = 2mono
workers = 4
